### ISSUE TITLE
Missing WebView events: Navigating / Navigated / ReloadRequested

### ISSUE THREAD

**Issue by cornem** [dotnet/MobileBlazorBindings#231]
I'm trying to use a `WebView` for OIDC sign in. After logging in, the identity service redirects to another URL. In non-Blazor apps, I'd subscribe to the `WebView.Navigating` event to handle the redirect and read authorization codes or tokens.

However, these events appear to be missing in the `WebView` provided by `MobileBlazorBindings`. Is there a way to subscribe to this event currently?

Version I'm using: 0.5.50-preview

**Comment by Eilon** [comment]
Tagging @jspuij who is looking at auth.

@cornem - how are you using WebView right now, can you show a small code snippet?

**Comment by cornem** [comment]
@Eilon Here's what I typically do when using a `WebView` for authentication:

1. Call `PrepareLoginAsync()` on `OidcClient` (from `IdentityModel.OidcClient`)
2. This generates an instance of `AuthorizationState` with a `StartUrl` and `RedirectUrl`
3. Pass the `StartUrl` to the `WebView`, user will sign in on the web page
4. Identity provider redirects to `RedirectUrl` when sign-in has completed

In a non-Blazor Xamarin Forms app I would subscribe to `WebView.Navigating` and pick up the auth process as soon as the user starts navigating to a URL that starts with `RedirectUrl`.

I have done this now by creating my own `WebView` component and handler, adding the `Navigating` and `Navigated` events. If helpful, I could make a PR on the original classes to implement this.

```csharp
public class MyWebView : Microsoft.MobileBlazorBindings.Elements.WebView
{
    static MyWebView()
    {
        ElementHandlerRegistry
            .RegisterElementHandler<MyWebView>(renderer => new MyWebViewHandler(renderer, new WebViewExtended(new DefaulBlazorErrorHandler())));
    }

    [Parameter] public EventCallback<WebNavigatedEventArgs> OnNavigated { get; set; }

    [Parameter] public EventCallback<WebNavigatingEventArgs> OnNavigating { get; set; }

    protected override void RenderAttributes(AttributesBuilder builder)
    {
        base.RenderAttributes(builder);

        builder.AddAttribute("onnavigated", EventCallback.Factory.Create<WebNavigatedEventArgs>(this, e => OnNavigated.InvokeAsync(e)));
        builder.AddAttribute("onnavigating", EventCallback.Factory.Create<WebNavigatingEventArgs>(this, e => OnNavigating.InvokeAsync(e)));
    }
}
```

And the corresponding handler:

```csharp
public class MyWebViewHandler : Microsoft.MobileBlazorBindings.Elements.Handlers.WebViewHandler
{
    private ulong _onNavigatedEventHandlerId;
    private ulong _onNavigatingEventHandlerId;

    public MyWebViewHandler(NativeComponentRenderer renderer, WebViewExtended control) 
        : base(renderer, control)
    {
        ConfigureEvent(
            eventName: "onnavigating",
            setId: id => _onNavigatingEventHandlerId = id,
            clearId: id => { if (_onNavigatingEventHandlerId == id) { _onNavigatingEventHandlerId = 0; } });

        Control.Navigating += (object sender, WebNavigatingEventArgs args) =>
        {
            if (_onNavigatingEventHandlerId != default)
            {
                renderer.Dispatcher.InvokeAsync(() => renderer.DispatchEventAsync(_onNavigatingEventHandlerId, null, args));
            }
        };

        ConfigureEvent(
            eventName: "onnavigated",
            setId: id => _onNavigatedEventHandlerId = id,
            clearId: id => { if (_onNavigatedEventHandlerId == id) { _onNavigatedEventHandlerId = 0; } });

        Control.Navigated += (object sender, WebNavigatedEventArgs args) =>
        {
            if (_onNavigatedEventHandlerId != default)
            {
                renderer.Dispatcher.InvokeAsync(() => renderer.DispatchEventAsync(_onNavigatedEventHandlerId, null, args));
            }
        };
    }
}
```

**Comment by jspuij** [comment]
Hi @cornem. The Navigating and Navigated events are indeed not exposed ATM. We will expose them in the future. A few things need to happen for that:

1) The events need to be exposed on the (Blazor) Webview component.
2) The renderers need to be fixed to actually trigger the events. ATM only the Android renderer will properly trigger the Navigating and Navigated events. This is because the Android renderer is based on the original Xamarin Renderer, whereas the Windows, iOS and macOS renderers were written from scratch and this was not taken into account. The native events are just not wired to the platform independent encapsulating Xamarin webview. It's on my todo list to fix this.

However using a webview for auth is discouraged on iOS, macOS and Android. The webview does not show an URL and the users cannot inspect the certificate easily, opening the door to MITM attacks. That is why on iOS and macOS and Android steps were taken to block this. E.g. on mobile platforms redirecting to a custom scheme in a normal webview isn't allowed anymore. Likewise Google servers detect an embedded webview and will block auth based on the User agent.
I would not use a webview a.t.m. for auth.

https://www.gluu.org/blog/webviews-are-bad-use-appauth/
https://www.oauth.com/oauth2-servers/oauth-native-apps/use-system-browser/

What we will add in the next preview (possible in the nightlies already in a week or so) is add Auth to MBB based on the OS intrinsic mechanisms of the platform. Xamarin Essentials exposes these as [WebAuthenticator ](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios)for iOS, macOS and Android. We will write our own version for windows.

The advantage of using a platform secure webview or custom tabs is that extensions are allowed to run (so password managers work), whereas in a normal webview they won't. 

You can find some early preview videos here:

https://youtu.be/-mqT1uOVmco
https://youtu.be/X4PwEf3VC3g
https://youtu.be/S_ppoP-LftE

Unfortunately the logout experience is poor on iOS and macOS. There is an additional popup requesting login, when you actually logout. This can be prevented by using a private browsing session (not sharing cookies with the main browser), but onfortunately Xamarin essentials does not expose that parameter. We will ask the Xamarin team to add this feature.

**Comment by cornem** [comment]
I can confirm the stuff above works on Android, haven't tested it on iOS, but I conclude from your comment that won't work. I wasn't aware of the `WebAuthenticator` and I'll look into that.

**Comment by jspuij** [comment]
I have an initial implementation of Autb in #215. It's just not finished yet, but will take a week or two more. Then it will be part of MBB.
