### ISSUE TITLE
Native components inside of web components

### ISSUE THREAD

**Issue by qrzychu** [dotnet/MobileBlazorBindings#340]
Hi, first of all, great job :)

The post came out a bit long and disorganized, so here is TLDR:

- Template does not work in Rider, but does work in VS (kind of)
- Can I mix Web and Native components? Will I be able to with MAUI?
- How does the CounterState sample work? Is it the same object within the BlazorWebView and hosting app or is a copy kept in sync?
- Is there a way to "hide" the fact that part of the app is HTML? I'm talking about context menu, back with mouse button etc

----------------------------

I got super excited about this whole thing, because in my mind I could just replace WPF app with a Blazor Hybrid, hosted in a BlazorWebView. Sounds great. 

However, I spun up the template aaand... Under Rider it opens, but the web view never loads. When I run the app just from bin directory, it works, in VS it also works, but VS starts showin errors after clicking around without modyfing anything, but it still compiles and runs fine. Both Rider and VS updated today, but that's really irrelevant.

![image](https://user-images.githubusercontent.com/4633810/109702865-15bd4080-7b95-11eb-9d9e-34aa2abecdd7.png)

First thing I wanted to try was to put a "native" component inside of web razor component, so I wrote:

```
@page "/nativetest"

<h3>NativeTest</h3>

<img src="http://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"/>

<StackLayout>
    @*<Entry @bind-Text="Text"/>*@
    @if (GoogleLogo != null)
    {
        <p>Second Google logo</p>
        <Image Source="GoogleLogo"/>
    }
    else { 
        <p>Second logo is null</p>
    }
</StackLayout>

@code {
    string Text { get; set; }
    ImageSource GoogleLogo { get; set; }

    protected override void OnInitialized()
    {
        GoogleLogo = ImageSource.FromUri(new Uri(@"http://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"));
        StateHasChanged();
    }
}
```
The result is not exactly what I expected:
![image](https://user-images.githubusercontent.com/4633810/109701598-7b103200-7b93-11eb-9dcb-5e8939508301.png)

I imagine that getting this to work in Xamarin.Forms will be super hard, but how about MAUI? Is there even consideration for this?

My thought process is that I would love to write the whole app as HTML with CSS, and then maybe a small piece would be much better in a native form (can't come up with a good example right now, but maybe some libs like CadLib would provide MAUI component for viewing and manipulating DXFs?). That would mean that I have to do the whole app natively, which would not be that bad, but I loose CSS.

I get that there will be some kind of styling system later, but will that make the whole hybrid thing obsolete?

Also, I have a question about the sample. Does Blazor use the `CounterObject`, as in it's the EXACT same object in memory? Or is it a copy kept in sync?

Last thing, is there a default way to disable BlazorWebView default controls like right click context menu, go back with side mouse button etc?

I'm sorry for the unorganized gibberish, I just got super excited about the concept, but trying it spawned tons of questions.

**Comment by Eilon** [comment]
No worries, a lot to unpack here, but I thank you for trying out this project and sharing your experience!

> Template does not work in Rider, but does work in VS (kind of)

I've never used Rider but I know some people have been successful with it for Mobile Blazor Bindings but some have also had issues.

The errors you see in VS are design-time only errors and don't affect the operation of the program. The root bug is logged here: https://github.com/dotnet/aspnetcore/issues/26647

For now you can ignore those errors (I don't know of any way to make them go away; they're just annoying!).

> Can I mix Web and Native components? Will I be able to with MAUI?

You can host a BlazorWebView with web UI among native components, but not the other way around. This is the same wherever the BlazorWebView control is used: Xamarin.Forms, WPF, WinForms, and, in the future, .NET MAUI. You cannot host native controls in the web UI. This is because the BlazorWebView is itself a native control just like any other native control. But there's no general way of hosting native UI in web UI unless you try to overlay it by setting Z-index on a native control to make it _appear_ on top of the web UI, but it won't actually be _in_ the web UI.

> How does the CounterState sample work? Is it the same object within the BlazorWebView and hosting app or is a copy kept in sync?

It is 100% the exact same object, there is only 1 instance of it, and it is shared everywhere in the app. It's not as magical as perhaps it sounds: the entire app is written in .NET, all your code is .NET/C# code, it's just that part of the app creates/updates native controls, and part of the app creates/updates HTML/web UI inside a native BlazorWebView control.

> Is there a way to "hide" the fact that part of the app is HTML? I'm talking about context menu, back with mouse button etc

Yes you can hide/disable just about anything. I haven't experimented with it much, so I can't show any code/samples, but each native web view has the ability to control how much of its own UI is seen, such as contact menus, nav, etc.

**Comment by Eilon** [comment]
BTW if there's anything that I didn't answer or I've misunderstood, please let me know and I will try to answer!

**Comment by Dreamescaper** [comment]
> The errors you see in VS are design-time only errors and don't affect the operation of the program. The root bug is logged here: dotnet/aspnetcore#26647
> For now you can ignore those errors (I don't know of any way to make them go away; they're just annoying!).

Personally I simply added namespace alias (`@using XF = Xamarin.Forms`) to workaround this issue. I need to add XF qualifier to all Xamarin.Forms arguments (e.g. `XF.FontAttributes`, `XF.Color`, etc) though...

**Comment by Eilon** [comment]
Ah yes that is a good workaround!

**Comment by qrzychu** [comment]
Thank's a lot fot fast response - now it's more clear to me how the BlazorWebView works.

As for hosting native component inside of WebComponent, I read up a bit more on MAUI. It looks like they want to support CSS for styling, which is great. I dislike the fact that they chose the Xamarin version of XAML over WPF (which is pretty magical when you get the hang of it), but tey also want to support "canvas drawn renderers" for controls. Maybe there is a way to switch to that when native component is inside of web component?

I'm just trowing this thought out there, maybe someone will pick it up.

As for the bindings themselves, I think I prefer them over the Xamarin flavour of XAML, so I hope this makes its way into MAUI release.  Are there any plans to suport hot reload of razor native components? Or is it alredy there but it just dosn't work yet since it's preview?

**Comment by Eilon** [comment]
The main problem with hosting native components inside web components is that there's no easy way to get "into" the WebView aside from giving it HTML/CSS to render. Those controls are all about taking HTML/CSS and drawing it on a screen - just like a web browser (because it _is_ the same code as a web browser). Waaaaaay back in the day you had Internet Explorer with ActiveX controls that could do that, but those days are long gone.

Support for Blazor for native controls will continue in this experimental project as an alternative to using XAML or code-based UI.

Regarding hot reload, it's definitely an area we're looking at for every aspect of .NET, including Blazor UI projects. There's nothing at all yet for Mobile Blazor Bindings but for .NET MAUI and Blazor Desktop it's something we'd like to deliver.

**Comment by qrzychu** [comment]
Thanks a lot. Maybe there is a "hard way" to get native inside WebView, just maybe. I think this issue can be closed.

Do you know any resources that spek of how MAUI would use CSS for styling native controls?

**Comment by Dreamescaper** [comment]
I think that it will be same as in Xamarin.Forms (considering that MAIU is basically a rebranded XF).
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/

**Comment by Eilon** [comment]
We have some Mobile Blazor Bindings specific docs on CSS as well: https://docs.microsoft.com/en-us/mobile-blazor-bindings/ui/css-styles

Closing this issue because I think the key discussions are complete. Thanks!
