### ISSUE TITLE
How to include scoped CSS from razor class library?

### ISSUE THREAD

**Issue by GermanGolota** [dotnet/MobileBlazorBindings#384]
Hi, I would like to include razor class library, that uses scoped css. Is there any way to support that?

**Comment by Eilon** [comment]
Hi @GermanGolota I think that isn't supported right now in Mobile Blazor Bindings due to some limitations of how static web assets work. However, we are releasing the official BlazorWebView control for .NET MAUI, WPF, and WinForms, as part of the .NET 6 release, and there we will have full support for scoped CSS (though there are some bugs with it right now).
