### ISSUE TITLE
Blazor Hybrid App - Windows

### ISSUE THREAD

**Issue by bomneris** [dotnet/MobileBlazorBindings#402]
Hello, sorry if I am repeating an issue or if this is something I missed but after I install default Hybrid add from template "dotnet new blazorhybrid -o FirstBlazorHybridApp" and try to run windows project I get this errror
![image](https://user-images.githubusercontent.com/64839225/132650436-6d3aa0da-be77-45b5-9b1a-a686f68b7385.png)

I cant find any details why am I getting this maybe someone could help?

**Comment by TheCakeMonster** [comment]
I've been having this problem too, but @Eilon managed to point me in the right direction to fix it.

An upgrade to Microsoft Edge last week is the root cause. The fix is to add a PackageReference to Microsoft.Web.WebView2 version 1.0.961.33 to your Windows UI project. Use of this later version of the WebView2 adapter resolves the failure.

Related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/1714

**Comment by bomneris** [comment]
@TheCakeMonster Works like a charm!
